#include <Arduino.h>
#include <model.h>

unsigned long preTime = 0;
unsigned long nowTime = 0;
unsigned long interval = 100000; //Step size setted in Simulink

void initLib(void);

void setup() {
  // put your setup code here, to run once:
  initLib(); //initialize fcn 
  preTime = micros();
}

void loop() {
  // put your main code here, to run repeatedly:
  nowTime = micros();
  if (nowTime - preTime > interval){
    model_step();  //step fcn generated by simulink
    preTime = nowTime;
  }
}
